function [last_level] = amg_coarsen_plot3D(amg_grids, xyz)
%AMG_COARSEN_PLOT3D plots grids generated by AMG setup routine
%
% last_level = amg_coarsen_plot3D(amg_grids, xyz)
%
%  Inputs:
%  amg_grids     generated using 'amg_grids_setup'
%  xyz           generated by IFISS3D, contains grid points
%              
%  Output:
%  last_level    last_level(i) contains the value of the last level in 
%                which point i exists
%
%  PIFISS function: DJS; 31 January 2007. 
%  Copyright (c) 2007 by J. Boyle

n_levels = length(amg_grids);           % number of levels
n_points = length(amg_grids(1).A);      % number of points
last_level = ones(n_points,1);          % array to store last level for each point

level = n_levels;                       % start from last level
map = amg_grids(level).map_to_F;        % point i on level n corresponds to point map(i) on level n-1

while level > 1
    % update counts for C point in current level
    last_level(map) = last_level(map) + 1;

    if level > 2
        % get the map for the next level
        next_map = amg_grids(level-1).map_to_F;

        % map points in current level into new position on next level
        last_level_next = ones(n_points,1);
        last_level_next(next_map(map)) = last_level(map);

        last_level = last_level_next;
        map = next_map;
    end
    level = level - 1;
end

len = sqrt(n_points);
points = (1:n_points)';


for level = 1:n_levels
    points = find(last_level >= level);

    figure(27)
    plot3(xyz(points, 1), xyz(points,2),xyz(points,3),'*b')
    axis([-1 1 -1 1 -1 1]); axis square;
    xlabel(num2str(level))
    if level < n_levels
        title('Press a key for next level')
        pause
    end
end
title('Finished')

